import type { Metadata } from "next";

import '@mantine/core/styles.css';
import { ColorSchemeScript, MantineProvider, mantineHtmlProps } from '@mantine/core';

import "./globals.css";
import Footer from "@/components/footer/component";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
	return (
		<html lang="en" {...mantineHtmlProps}>
			<head>
				<ColorSchemeScript />
			</head>
			<body>
				<MantineProvider defaultColorScheme="dark">
					<div style={{height: "100vh"}}>
						{children}
					</div>
					<Footer />
				</MantineProvider>
			</body>
		</html>
	);
}
